package uz.pdp.springsecurity.enums;

public enum Permissions {

    ADD_BUSINESS,
    EDIT_BUSINESS,
    VIEW_BUSINESS,
    DELETE_BUSINESS,

    EDIT_SUBSCRIPTION,
    VIEW_SUBSCRIPTION,
    CREATE_SUBSCRIPTION,
    ACTIVE_MY_SUBSCRIPTION,

    //WRITE SUPER ADMIN PERMISSIONS ABOVE

    ADD_ADDRESS,
    EDIT_ADDRESS,
    VIEW_ADDRESS,
    DELETE_ADDRESS,

    UPLOAD_MEDIA,
    DOWNLOAD_MEDIA,
    VIEW_MEDIA_INFO,
    DELETE_MEDIA,

    ADD_BRANCH,
    EDIT_BRANCH,
    VIEW_BRANCH_ADMIN,
    VIEW_BRANCH,
    DELETE_BRANCH,

    ADD_BRAND,
    EDIT_BRAND,
    VIEW_BRAND,
    DELETE_BRAND,

    ADD_CATEGORY,
    EDIT_CATEGORY,
    VIEW_CATEGORY,
    VIEW_CATEGORY_ADMIN,
    DELETE_CATEGORY,
    ADD_CHILD_CATEGORY,

    ADD_CURRENCY,
    EDIT_CURRENCY,
    VIEW_CURRENCY,
    DELETE_CURRENCY,

    ADD_CUSTOMER,
    EDIT_CUSTOMER,
    VIEW_CUSTOMER,
    VIEW_CUSTOMER_ADMIN,
    DELETE_CUSTOMER,

    ADD_MEASUREMENT,
    EDIT_MEASUREMENT,
    VIEW_MEASUREMENT,
    VIEW_MEASUREMENT_ADMIN,
    DELETE_MEASUREMENT,

    ADD_OUTLAY,
    EDIT_OUTLAY,
    VIEW_OUTLAY,
    VIEW_OUTLAY_ADMIN,
    DELETE_OUTLAY,

    ADD_PRODUCT,
    EDIT_PRODUCT,
    VIEW_PRODUCT,
    VIEW_PRODUCT_ADMIN,
    DELETE_PRODUCT,

    ADD_ROLE,
    EDIT_ROLE,
    VIEW_ROLE,
    VIEW_ROLE_ADMIN,
    DELETE_ROLE,

    ADD_SUPPLIER,
    EDIT_SUPPLIER,
    VIEW_SUPPLIER,
    VIEW_SUPPLIER_ADMIN,
    DELETE_SUPPLIER,

    ADD_USER,
    EDIT_USER,
    VIEW_USER,
    VIEW_USER_ADMIN,
    DELETE_USER,
    EDIT_MY_PROFILE,

    ADD_TRADE,
    EDIT_TRADE,
    VIEW_TRADE,
    VIEW_TRADE_ADMIN,
    DELETE_TRADE,
    DELETE_MY_TRADE,
    VIEW_MY_TRADE,

    ADD_PAY_METHOD,
    EDIT_PAY_METHOD,
    VIEW_PAY_METHOD,
    VIEW_PAY_METHOD_ADMIN,
    DELETE_PAY_METHOD,

    ADD_PAY_STATUS,
    EDIT_PAY_STATUS,
    VIEW_PAY_STATUS,
    VIEW_PAY_STATUS_ADMIN,
    DELETE_PAY_STATUS,

    ADD_PURCHASE,
    EDIT_PURCHASE,
    VIEW_PURCHASE,
    VIEW_PURCHASE_ADMIN,
    DELETE_PURCHASE,


    ADD_EXCHANGE,
    EDIT_EXCHANGE,
    VIEW_EXCHANGE,
    VIEW_EXCHANGE_ADMIN,
    DELETE_EXCHANGE,

    VIEW_BENEFIT_AND_LOST,


    ADD_CUSTOMER_GROUP,
    DELETE_CUSTOMER_GROUP,
    EDIT_CUSTOMER_GROUP,
    VIEW_CUSTOMER_GROUP,

    ADD_TAX,
    DELETE_TAX,
    EDIT_TAX,
    VIEW_TAX,

    ADD_PRODUCT_TYPE,
    GET_PRODUCT_TYPE,
    UPDATE_PRODUCT_TYPE,
    DELETE_PRODUCT_TYPE,

    GET_EXCEL,
    POST_EXCEL,

    VIEW_INFO,

    GET_TARIFF,
    CREATE_TARIFF,
    EDIT_TARIFF,
    DELETE_TARIFF,

    CREATE_CONTENT,
    EDIT_CONTENT,
    GET_CONTENT,
    DELETE_CONTENT,

    CREATE_COURSE,
    EDIT_COURSE,
    GET_COURSE,
    DELETE_COURSE,

    CREATE_PRODUCTION,
    GET_PRODUCTION,

    GET_BUSINESS_ALL_AMOUNT,

    GET_TO_CHOOSE_A_TARIFF,

    VIEW_REPORT
}
